# Generated by Django 5.2.8 on 2025-11-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('faculty', models.CharField(max_length=256)),
                ('group_name', models.CharField(max_length=64)),
                ('theme_name', models.TextField()),
                ('years', models.CharField(max_length=32)),
                ('files', models.FileField(upload_to='student_files/')),
            ],
        ),
    ]
